name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "42 3 * * 6" # random

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master
